### ISSUE TITLE
hdf4 hdfi.h include goes away in the next release

### ISSUE THREAD

**Issue by schwehr** [fhs/pyhdf#70]
The `hdfi.h` include here https://github.com/fhs/pyhdf/blob/e8f87adb3f308fc6dc6105aa631e2c659da8f4e6/pyhdf/hdfext.i#L206 goes away in hdf4 here: https://github.com/HDFGroup/hdf4/commit/ec211cddbeb8c5bebe7404254a42cc6d686daa6f

For my build, I was able to just remove that line and things built and tested fine.

Note that HDF4 has been undergoing a ton of cleanup recently. It's worth taking a careful look at pyhdf to coordinate with hdf4 before its next release

@derobins

**Comment by derobins** [comment]
HDF4 has historically had a very poor separation of public vs. private interfaces. In 4.3.0, which will release at the end of February, we've finally stopped deploying internal header files like `hdfi.h`. For people who are using the public API, as defined in the reference manual, user guide, etc., you should no longer need `hdfi.h`. FWIW, you didn't need to include that file at any time, since it was pulled in by `hdf.h`.

Once you've stopped including `hdfi.h`, ping us over at https://github.com/HDFGroup/hdf4 and we'll create a CI action to make sure pyhdf doesn't break as we change things.

**Comment by sebastic** [comment]
HDF 4.3.0 has been released, with which pyhdf fails to build as reported in [Debian Bug #1068384](https://bugs.debian.org/1068384).

**Comment by thebaptiste** [comment]
Could you please provide a new release with this fix ? I'm using HDF 4.3.0 and I can't install pyhdf from sources on Python 3.12 anymore

**Comment by fhs** [comment]
@thebaptiste A new version has been released with the fix.

**Comment by thebaptiste** [comment]
@fhs Thanks a lot !
